# Generated by Django 3.2.15 on 2023-07-21 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, unique=True, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Широта')),
                ('long', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Долгота')),
                ('geo_request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
            ],
        ),
    ]
