# Generated by Django 3.2.15 on 2023-07-15 13:50

from django.db import migrations


def fill_order_items_cost(apps, schema_editor):
    OrderItems = apps.get_model('foodcartapp', 'OrderItems')
    order_items = list(OrderItems.objects.all())
    print(order_items)
    old_order_items = [OrderItems(
        id=item.id,
        price=item.product.price,
        product=item.product,
        order=item.order,
        quantity=item.quantity
    ) for item in order_items if not item.price]
    print(old_order_items)
    OrderItems.objects.bulk_update(old_order_items, ['price'])


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_orderitems_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_items_cost),
    ]
