# Generated by Django 3.2.15 on 2023-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230715_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('н', 'Необработанный'), ('г', 'В работе'), ('д', 'В доставке'), ('з', 'Завершен')], db_index=True, default='new', max_length=10),
        ),
    ]
