# Generated by Django 3.2.15 on 2023-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('н', 'Необработанный'), ('г', 'В работе'), ('д', 'В доставке'), ('з', 'Завершен')], db_index=True, default='н', max_length=10, verbose_name='Статус'),
        ),
    ]
