# Generated by Django 3.2.15 on 2023-07-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230718_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('нал', 'Наличностью'), ('безнал', 'Электронно')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
