# Generated by Django 3.2.15 on 2023-07-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geotools', '0001_initial'),
        ('foodcartapp', '0048_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_orders', to='geotools.location', verbose_name='Координаты клиента'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_restaurants', to='geotools.location', verbose_name='Координаты ресторана'),
        ),
    ]
