# Generated by Django 3.2.15 on 2023-08-02 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230721_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='registered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('unspecified', 'Не указано'), ('cash', 'Наличностью'), ('cashless', 'Электронно')], db_index=True, default='unspecified', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'Необработанный'), ('w', 'В работе'), ('d', 'В доставке'), ('c', 'Завершен')], db_index=True, default='n', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
